version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=drinkonomy
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - app-network

  webserver:
    depends_on:
      - db
      - php
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ../:/wordpress
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

  php:
    container_name: php
    build: ./php
    depends_on:
      - db
    image: php:7.2-fpm-alpine
    networks:
      - app-network
    environment:
      DB_NAME: drinkonomy
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: db
    volumes:
      - ./logs/xdebug:/data/debug:delegated
      - ../:/wordpress:delegated
    command: ['php-fpm']
